### PR TITLE
Trunk/apertium spa ita

### PR DESCRIPTION
**Pull request by jimregan**
Making this the master branch would probably solve #1

### CODE REVIEW

**Comment by jimregan** [comment]
(dunno why I did that as a pull request, nvm)

**Comment by ftyers** [comment]
Shouldn't we delete this if spa-ita exists ? That's what I did with es-an (for spa-arg)

**Comment by jimregan** [comment]
That one has partial history, this one has full history. Makes more sense to rename this and change the master branch (it's really not difficult)

**Comment by ftyers** [comment]
@jimregan ok, whichever :D 

@sushain97 @shardulc perhaps this should be done for all pairs where this happened ?

**Comment by jimregan** [comment]
You might want to ask those guys to re-import es-an, because it's missing a lot

**Comment by sushain97** [comment]
`es-an` was deleted by Fran about 2 hours ago. 

```
apertium@wolf:~/apertium-on-github/apertium-spa-arg.git$ git rev-list --count master
41
```

`spa-arg` has all the history that I can get you.

**Comment by jimregan** [comment]
It turns out es-an had a particularly messy history -- I think this was back in the time when sourceforge would go 'svn mv? sure! ok, rm. uh.... what was that other thing you wanted?'

**Comment by sushain97** [comment]
LOL. There's some conversation in Apertium-stuff about bringing es-an back as an archived repository but @ftyers is opposed.

**Comment by jimregan** [comment]
https://github.com/apertium/apertium-spa-arg/pull/1

**Pull request closed without merging**
